export const LEVELS = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Light motor pool',
    upgradeCost: 0,
    unitTypes: ['harvester', 'motorcycle', 'buggy'],
    buildingTypes: ['cyard', 'power', 'refinery', 'barracks'],
  },
  {
    id: 'improved',
    name: 'Improved',
    description: 'Passive base defense',
    upgradeCost: 2500,
    unitTypes: ['tank'],
    buildingTypes: ['fence', 'gate'],
  },
  {
    id: 'advanced',
    name: 'Advanced',
    description: 'Air power and turrets',
    upgradeCost: 4500,
    unitTypes: ['plane'],
    buildingTypes: ['turret'],
  },
  {
    id: 'high',
    name: 'High',
    description: 'Strategic weapons',
    upgradeCost: 8000,
    unitTypes: ['nuke_rocket', 'bio_rocket'],
    buildingTypes: ['laser', 'explosive_tower'],
  },
];

export const BUILDING_DEFS = {
  cyard: {
    name: 'Construction Yard',
    cost: 1000,
    duration: 8.0,
    level: 'basic',
    gridWidth: 3,
    gridHeight: 3,
    maxHealth: 1500,
    powerProduction: 0,
    powerUsage: 0,
    height3D: 35,
  },
  power: {
    name: 'Power Plant',
    cost: 300,
    duration: 4.0,
    level: 'basic',
    gridWidth: 2,
    gridHeight: 2,
    maxHealth: 600,
    powerProduction: 100,
    powerUsage: 0,
    height3D: 25,
  },
  refinery: {
    name: 'Ore Refinery',
    cost: 2000,
    duration: 10.0,
    level: 'basic',
    gridWidth: 3,
    gridHeight: 2,
    maxHealth: 1000,
    powerProduction: 0,
    powerUsage: 40,
    height3D: 28,
  },
  barracks: {
    name: 'Motor Pool',
    cost: 500,
    duration: 6.0,
    level: 'basic',
    gridWidth: 2,
    gridHeight: 2,
    maxHealth: 800,
    powerProduction: 0,
    powerUsage: 20,
    height3D: 24,
  },
  fence: {
    name: 'Fence',
    cost: 120,
    duration: 2.0,
    level: 'improved',
    gridWidth: 1,
    gridHeight: 1,
    maxHealth: 450,
    powerProduction: 0,
    powerUsage: 0,
    height3D: 12,
    passiveDefense: true,
  },
  gate: {
    name: 'Gate',
    cost: 180,
    duration: 2.5,
    level: 'improved',
    gridWidth: 1,
    gridHeight: 1,
    maxHealth: 520,
    powerProduction: 0,
    powerUsage: 0,
    height3D: 10,
    passiveDefense: true,
    isGate: true,
  },
  turret: {
    name: 'Cannon Turret',
    cost: 900,
    duration: 7.0,
    level: 'advanced',
    gridWidth: 2,
    gridHeight: 2,
    maxHealth: 900,
    powerProduction: 0,
    powerUsage: 35,
    height3D: 28,
    weapon: { damage: 30, range: 230, cooldown: 1.2, projectile: 'shell', speed: 280 },
  },
  laser: {
    name: 'Laser Tower',
    cost: 1600,
    duration: 9.0,
    level: 'high',
    gridWidth: 2,
    gridHeight: 2,
    maxHealth: 1100,
    powerProduction: 0,
    powerUsage: 70,
    height3D: 36,
    weapon: { damage: 48, range: 280, cooldown: 0.8, projectile: 'laser', speed: 620 },
  },
  explosive_tower: {
    name: 'Explosive Tower',
    cost: 2100,
    duration: 11.0,
    level: 'high',
    gridWidth: 2,
    gridHeight: 2,
    maxHealth: 1250,
    powerProduction: 0,
    powerUsage: 85,
    height3D: 34,
    weapon: { damage: 76, range: 300, cooldown: 2.4, projectile: 'explosive', speed: 220 },
  },
};

export const UNIT_DEFS = {
  harvester: {
    name: 'Harvester',
    cost: 1000,
    duration: 12.0,
    level: 'basic',
    producer: 'refinery',
  },
  motorcycle: {
    name: 'Motorcycle',
    cost: 160,
    duration: 2.5,
    level: 'basic',
    producer: 'barracks',
    speed: 150,
    maxHealth: 42,
    damage: 9,
    attackRange: 130,
  },
  buggy: {
    name: 'Buggy',
    cost: 260,
    duration: 3.5,
    level: 'basic',
    producer: 'barracks',
    speed: 125,
    maxHealth: 90,
    damage: 14,
    attackRange: 150,
  },
  tank: {
    name: 'Tank',
    cost: 800,
    duration: 10.0,
    level: 'improved',
    producer: 'barracks',
    speed: 95,
    maxHealth: 250,
    damage: 45,
    attackRange: 200,
  },
  plane: {
    name: 'Plane',
    cost: 1200,
    duration: 9.0,
    level: 'advanced',
    producer: 'barracks',
    speed: 180,
    maxHealth: 130,
    damage: 36,
    attackRange: 240,
    flying: true,
  },
  nuke_rocket: {
    name: 'Nuclear Rocket',
    cost: 2400,
    duration: 14.0,
    level: 'high',
    producer: 'barracks',
    speed: 85,
    maxHealth: 95,
    damage: 130,
    attackRange: 330,
    projectile: 'nuke',
  },
  bio_rocket: {
    name: 'Bio Rocket',
    cost: 1900,
    duration: 12.0,
    level: 'high',
    producer: 'barracks',
    speed: 90,
    maxHealth: 100,
    damage: 95,
    attackRange: 310,
    projectile: 'bio',
  },
};

export function getLevelIndex(levelId) {
  return LEVELS.findIndex(level => level.id === levelId);
}

export function isUnlockedAt(currentLevelIndex, def) {
  return currentLevelIndex >= getLevelIndex(def.level);
}
